src/profiles/urls.py
from django.urls import path
from .views import UserListView, UserChartView

app_name = 'profiles'

urlpatterns = [
    path('', UserListView.as_view(), name='user-list'),
    path('<profile_id>/', UserChartView.as_view(), name='user-chart'),
]

src/skills/urls.py
from django.urls import path
from .views import skill_view, UserChartView, AllChartView

app_name = 'skills'

urlpatterns = [
    path('', skill_view, name='my-skills'),
    path('all/', AllChartView.as_view(), name='all-skills'),
    path('<profile_id>/', UserChartView.as_view(), name='user-skills'),
]

src/skills_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('skills/', include('skills.urls', namespace='skills')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
# Create your models here.


class Profile(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    avatar = models.ImageField(upload_to='uploads/img', validators=[
                               FileExtensionValidator(allowed_extensions=['png'])], blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    @property
    def get_created(self):
        return self.created.strftime("%m/%d/%Y, %H:%M:%S")

    def __str__(self):
        return "{}-{}".format(self.name, self.get_created)

src/skills/models.py
from django.db import models
from profiles.models import Profile
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.


class Skill(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=220)
    score = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)])

    def __str__(self):
        return "{}-{}-{}".format(self.user, self.name, self.score)

src/profiles/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from .models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class UserChartView(LoginRequiredMixin, TemplateView):
    template_name = 'profiles/user_skills.html'

    def get_object(self):
        pk = self.kwargs.get('profile_id')
        return pk

    def get_context_data(self, **kwargs):
        context = super(UserChartView, self).get_context_data(**kwargs)
        profile = Profile.objects.get(name__id=self.get_object())
        qs = profile.skill_set.all()
        context["qs"] = qs
        return context


class UserListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/user_list.html'

src/skills/views.py
from django.shortcuts import render, redirect
from django.forms import inlineformset_factory
from .models import Skill
from profiles.models import Profile
from django.views.generic import TemplateView
from django.db.models import Sum
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# Create your views here.


class AllChartView(LoginRequiredMixin, TemplateView):
    template_name = "skills/all_charts.html"

    def get_context_data(self, **kwargs):
        context = super(AllChartView, self).get_context_data(**kwargs)
        qs = Skill.objects.values('name').annotate(total=Sum('score'))
        context["qs"] = qs
        return context


class UserChartView(LoginRequiredMixin, TemplateView):
    template_name = 'skills/user_skills.html'

    def get_object(self):
        pk = self.kwargs.get('profile_id')
        return pk

    def get_context_data(self, **kwargs):
        context = super(UserChartView, self).get_context_data(**kwargs)
        profile = Profile.objects.get(name__id=self.get_object())
        qs = profile.skill_set.all()
        context["qs"] = qs
        return context


@login_required
def skill_view(request):
    user_id = request.user.id
    profile = Profile.objects.get(pk=user_id)

    SkillFormset = inlineformset_factory(
        Profile, Skill, fields='__all__', extra=1, can_delete=True)

    formset = SkillFormset(request.POST or None, instance=profile)
    if formset.is_valid():
        formset.save()

        return redirect('skills:my-skills')

    qs = profile.skill_set.all()

    context = {
        'formset': formset,
        'qs': qs,
    }

    return render(request, 'skills/add.html', context)

src/skills_proj/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'main/home.html', {})

src/profiles/templates/profiles/user_list.html
{% extends 'base.html' %}

{% block title %}user list{% endblock title %}

{% block content %}

<table class="ui single line table center aligned">
  <thead>
    <tr>
      <th>Username</th>
      <th>Joined date</th>
      <th>Skills</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in object_list %}
    <tr>
      <td>{{obj.name}}</td>
      <td>{{obj.created|date}}</td>
      <td>
        <a href="{% url 'profiles:user-chart' obj.pk %}">
        <button class="ui primary button">
            See
        </button>
        </a>
      </td>
    </tr>
{% endfor %}
  </tbody>
</table>

{% endblock content %}

src/profiles/templates/profiles/user_skills.html
{% extends 'base.html' %}

{% block title %}user skills{% endblock title %}

  
{% block scripts %}
<script>
$(document).ready(function(){

    getColor =() =>{
        r = getColorRange(0,255)
        g = getColorRange(0,255)
        b = getColorRange(0,255)
        op = 0.8
        color = 'rgb(' + r + ',' + g + ',' + b + ',' + op + ')'
        return color
    }

    getColorRange=(min, max)=>{
        return Math.floor(Math.random() * (max-min)) + min
    }
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: [{% for item in qs %}'{{item.name}}',{% endfor %}],
            datasets: [{
                label: '# of Votes',
                data: [{% for item in qs %}{{item.score}},{% endfor %}],
                backgroundColor: [{% for item in qs %}getColor(),{% endfor %}],
                borderColor: 'rgba(255, 159, 64, 1)',
                borderWidth: 2,
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
});
</script>
{% endblock scripts %}

{% block content %}
    <canvas id="myChart" width="400" height="200"></canvas>
{% endblock content %}

src/skills/templates/skills/add.html
{% extends 'base.html' %}

{% block title %}my skills{% endblock title %}

  
{% block scripts %}
<script>
$(document).ready(function(){
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [{% for item in qs %}'{{item.name}}',{% endfor %}],
            datasets: [{
                label: '# of points',
                data: [{% for item in qs %}{{item.score}},{% endfor %}],
                backgroundColor: 'rgba(255, 99, 132, 0.5)',
                borderColor: 'rgba(255, 159, 64, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
});
</script>
{% endblock scripts %}

{% block content %}
<div class="ui grid">
    <div class="four wide column">
        <form action="" method="POST" class="form ui" autocomplete="off">
            {% csrf_token %}
            {{formset.as_p}}
            <button class="secondary button ui" type="submit">Send</button>
        </form>
    </div>
    <div class="twelve wide column">
        <canvas id="myChart" width="400" height="300"></canvas>
    </div>
</div>

{% endblock content %}

src/skills/templates/skills/all_charts.html
{% extends 'base.html' %}

{% block title %}my skills{% endblock title %}

  
{% block scripts %}
<script>
$(document).ready(function(){
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [{% for item in qs %}'{{item.name}}',{% endfor %}],
            datasets: [{
                label: '# of points',
                data: [{% for item in qs %}{{item.total}},{% endfor %}],
                backgroundColor: 'rgba(44, 130, 201, 0.5)',
                borderColor: 'rgba(0, 0, 0, 1)',
                borderWidth: 1,
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
});
</script>
{% endblock scripts %}

{% block content %}

<canvas id="myChart" width="400" height="200"></canvas>

{% endblock content %}

src/skills/templates/skills/user_skills.html
{% extends 'base.html' %}

{% block title %}user skills{% endblock title %}

  
{% block scripts %}
<script>
$(document).ready(function(){

    getColor =() =>{
        r = getColorRange(0,255)
        g = getColorRange(0,255)
        b = getColorRange(0,255)
        op = 0.8
        color = 'rgb(' + r + ',' + g + ',' + b + ',' + op + ')'
        return color
    }

    getColorRange=(min, max)=>{
        return Math.floor(Math.random() * (max-min)) + min
    }
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: [{% for item in qs %}'{{item.name}}',{% endfor %}],
            datasets: [{
                label: '# of Votes',
                data: [{% for item in qs %}{{item.score}},{% endfor %}],
                backgroundColor: [{% for item in qs %}getColor(),{% endfor %}],
                borderColor: 'rgba(255, 159, 64, 1)',
                borderWidth: 2,
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
});
</script>
{% endblock scripts %}

{% block content %}
    <canvas id="myChart" width="400" height="300"></canvas>
{% endblock content %}

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <title>skill-site | {% block title %}{% endblock title %}</title>
  </head>
  <body>

  {% include 'navbar.html' %}
  {% block scripts %}
  {% endblock scripts %}

  <div class="container ui">
    {% block content %}
    {% endblock content %}
  </div>

  </body>
</html>

src/templates/main/home.html
{% extends 'base.html' %}

{% block title %}home{% endblock title %}

{% block content %}
<div class="ui icon message">
  <i class="inbox icon"></i>
  <div class="content">
    <div class="header">
      Do you have any questions?
    </div>
    <p>If so contact me on my emai: info@pyplane.com</p>
  </div>
</div>

<div class="ui segment">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget varius felis. Vestibulum id leo sem. Nulla facilisi. Vivamus accumsan nibh sit amet consequat scelerisque. Pellentesque pulvinar risus nec nunc pellentesque pulvinar. Morbi non ullamcorper purus, a pellentesque nibh. Aenean dapibus enim quam, porttitor vehicula lectus faucibus ut. Etiam a tortor in neque volutpat tincidunt eu in eros. Suspendisse et congue metus. In congue tristique enim, rutrum imperdiet elit lobortis sed. In mi libero, commodo id volutpat sit amet, congue nec eros. Aenean nec convallis mauris.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget varius felis. Vestibulum id leo sem. Nulla facilisi. Vivamus accumsan nibh sit amet consequat scelerisque. Pellentesque pulvinar risus nec nunc pellentesque pulvinar. Morbi non ullamcorper purus, a pellentesque nibh. Aenean dapibus enim quam, porttitor vehicula lectus faucibus ut. Etiam a tortor in neque volutpat tincidunt eu in eros. Suspendisse et congue metus. In congue tristique enim, rutrum imperdiet elit lobortis sed. In mi libero, commodo id volutpat sit amet, congue nec eros. Aenean nec convallis mauris.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget varius felis. Vestibulum id leo sem. Nulla facilisi. Vivamus accumsan nibh sit amet consequat scelerisque. Pellentesque pulvinar risus nec nunc pellentesque pulvinar. Morbi non ullamcorper purus, a pellentesque nibh. Aenean dapibus enim quam, porttitor vehicula lectus faucibus ut. Etiam a tortor in neque volutpat tincidunt eu in eros. Suspendisse et congue metus. In congue tristique enim, rutrum imperdiet elit lobortis sed. In mi libero, commodo id volutpat sit amet, congue nec eros. Aenean nec convallis mauris.
    </p>
    <br>
    <div class="sixteen wide column" style="text-align:center">
        <a href="{% url 'skills:my-skills' %}">
            <button class="massive primary ui button">
                <i class="chart line icon"></i> My skills
            </button>
        </a>
    </div>
</div>
{% endblock content %}

src/templates/navbar.html
{% url 'home' as path_home %}
{% url 'skills:my-skills' as path_my_skills %}
{% url 'skills:all-skills' as path_all_skills %}
{% url 'profiles:user-list' as path_users %}


<div class="ui inverted segment">
  <div class="ui inverted secondary pointing menu">
    <a href={{ path_home }} class="item {% if request.path == path_home %}active{% endif %}">
      Home
    </a>
    <a href={{ path_my_skills }} class="item {% if request.path == path_my_skills %}active{% endif %}">
      My skills
    </a>
    <a href={{ path_all_skills }} class="item {% if request.path == path_all_skills %}active{% endif %}">
      All skills
    </a>
    <a href={{ path_users }} class="item {% if request.path == path_users %}active{% endif %}">
      Users
    </a> 
  </div>
</div>